spring:
  application:
    name: class-service
  datasource:
    url: jdbc:mysql://localhost:3306/classdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate: { ddl-auto: update }
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085